import './style.css';
import { registerSW } from 'virtual:pwa-register';
import { buildPdf, formatAddress } from './pdf';
import { loadLocal, saveLocal, type SessionData, type StoredPhoto } from './storage';

const LABELS=['Akna / szellőző','Bal oldali szomszéd','Beazonosíthatóság','Bejárat','Bejárati ajtó','Bejárati előtér','Bojler / vízmelegítő','Dolgozószoba','Elektromos fűtőkazán','Elektromos tábla / elosztószekrény','Előszoba','Épület bejárata','Épület gázóra','Erkély','Étkező','Folyosó','Fürdőszoba','Fürdőszoba - részlet','Fürdőszobai radiátor / törölközőszárító','Garázs','Gardrób / beépített szekrény','Gázkazán / gázcirkó','Gázóra','Gyerekszoba','Hálószoba','Hálószoba - másik nézet','Homlokzat','Homlokzat - oldalnézet','Hőközpont','Hőmennyiségmérő','Hőszivattyú - beltéri egység','Hőszivattyú - kültéri egység','Jellemző nyílászáró','Jobb oldali szomszéd','Kapucsengő panel','Kazánszoba','Kert','Klíma - beltéri egység','Klíma - kültéri egység','Konyha','Konyha - másik nézet','Konyhai kiállások','Közlekedő','Lakás bejárata','Lakások elhelyezkedése','Lépcső','Lépcsőház','Lépcsőház - lift','Lift ajtó','Loggia','Mérőhely szekrény','Nappali','Nappali - másik nézet','Nappali termosztát','Nappali-konyha-étkező','Nyílászáró','Padlófűtés osztó-gyűjtő','Parkoló','Pince','Radiátor','Szeméttároló','Tároló','Terasz','Termosztát','Utcakép','Veranda','Villanyóra','Vízóra','WC'].sort((a,b)=>a.localeCompare(b,'hu'));
const TEMPLATES={lakás:['Utcakép','Homlokzat','Homlokzat','Jobb oldali szomszéd','Épület bejárata','Bejárati előtér','Lépcsőház','Lépcsőház - lift','Lakások elhelyezkedése','Lakás bejárata','Előszoba','Nappali','Konyha','Konyhai kiállások','Fürdőszoba','Fürdőszobai radiátor / törölközőszárító','WC','Hálószoba','Terasz','Nappali - másik nézet','Nappali termosztát','Jellemző nyílászáró','Elektromos tábla / elosztószekrény','Padlófűtés osztó-gyűjtő','Villanyóra','Vízóra'],ház:['Utcakép','Homlokzat','Homlokzat - oldalnézet','Bal oldali szomszéd','Jobb oldali szomszéd','Épület bejárata','Előszoba','Nappali','Konyha','Fürdőszoba','WC','Hálószoba','Gyerekszoba','Terasz','Kert','Garázs','Gázkazán / gázcirkó','Termosztát','Radiátor','Elektromos tábla / elosztószekrény','Villanyóra','Gázóra','Vízóra']};

const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const address=$<HTMLInputElement>('address'),hrsz=$<HTMLInputElement>('hrsz'),photoInput=$<HTMLInputElement>('photoInput'),sessionInput=$<HTMLInputElement>('sessionInput'),list=$('photoList'),status=$('status'),toast=$('toast'),dialog=$<HTMLDialogElement>('previewDialog'),preview=$('previewPages');
let photos:StoredPhoto[]=[]; let saveTimer=0; let deferredInstall:BeforeInstallPromptEvent|null=null;
interface BeforeInstallPromptEvent extends Event{prompt():Promise<void>;userChoice:Promise<{outcome:string}>}

function session():SessionData{return{version:1,address:address.value.trim(),hrsz:hrsz.value.trim(),photos,updatedAt:Date.now()}}
function notify(text:string){toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1700)}
function scheduleSave(){clearTimeout(saveTimer);saveTimer=window.setTimeout(()=>saveLocal(session()).catch(()=>status.textContent='Az automatikus mentés nem sikerült.'),350)}
function safeSession(value:unknown):SessionData{if(!value||typeof value!=='object')throw new Error('Érvénytelen munkafájl.');const v=value as Partial<SessionData>;if(typeof v.address!=='string'||typeof v.hrsz!=='string'||!Array.isArray(v.photos)||v.photos.length>150)throw new Error('Érvénytelen vagy túl nagy munkafájl.');const valid=v.photos.map((p:any)=>{if(!p||typeof p.dataUrl!=='string'||!/^data:image\/(jpeg|png|webp);base64,/.test(p.dataUrl)||p.dataUrl.length>12_000_000)throw new Error('A munkafájl nem támogatott képet tartalmaz.');return{id:typeof p.id==='string'?p.id:crypto.randomUUID(),dataUrl:p.dataUrl,caption:typeof p.caption==='string'?p.caption.slice(0,160):''}});return{version:1,address:v.address.slice(0,240),hrsz:v.hrsz.slice(0,80),photos:valid,updatedAt:Date.now()}}
function fileName(){return(formatAddress(address.value)||'ingatlan').replace(/[^\p{L}\p{N}\s-]/gu,'').trim().replace(/\s+/g,'_')}

function render(){list.replaceChildren();photos.forEach((photo,index)=>{const row=document.createElement('article');row.className='photo-row';const n=document.createElement('div');n.className='photo-number';n.textContent=String(index+1);const img=document.createElement('img');img.src=photo.dataUrl;img.alt=photo.caption||`${index+1}. fotó`;const input=document.createElement('input');input.className='caption';input.setAttribute('list','captionLabels');input.placeholder='Felirat';input.value=photo.caption;input.addEventListener('input',()=>{photo.caption=input.value.slice(0,160);img.alt=photo.caption||`${index+1}. fotó`;scheduleSave()});const actions=document.createElement('div');actions.className='row-actions';[['↑','Feljebb',-1],['↓','Lejjebb',1],['✕','Törlés',0]].forEach(([symbol,label,delta])=>{const b=document.createElement('button');b.className='icon-btn';b.textContent=String(symbol);b.title=String(label);b.setAttribute('aria-label',`${label}: ${index+1}. fotó`);if(delta===-1)b.disabled=index===0;if(delta===1)b.disabled=index===photos.length-1;b.onclick=()=>{if(delta===0)photos.splice(index,1);else{const [p]=photos.splice(index,1);photos.splice(index+Number(delta),0,p)}render();scheduleSave()};actions.append(b)});row.append(n,img,input,actions);list.append(row)});status.textContent=photos.length?`${photos.length} fotó · ${Math.ceil(photos.length/6)} oldal`:'Még nincs hozzáadott fotó.'}
function resize(file:File){return new Promise<string>((resolve,reject)=>{if(file.size>30_000_000)return reject(new Error(`${file.name}: a fájl túl nagy.`));const reader=new FileReader();reader.onerror=()=>reject(new Error(`${file.name}: nem olvasható.`));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error(`${file.name}: nem támogatott kép.`));img.onload=()=>{let w=img.naturalWidth,h=img.naturalHeight;const ratio=Math.min(1,1800/w,1200/h);w=Math.round(w*ratio);h=Math.round(h*ratio);const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');if(!ctx)return reject(new Error('A kép nem dolgozható fel.'));ctx.drawImage(img,0,0,w,h);resolve(c.toDataURL('image/jpeg',.86))};img.src=String(reader.result)};reader.readAsDataURL(file)})}
async function addFiles(files:FileList|File[]){status.textContent='Képek feldolgozása…';for(const file of Array.from(files)){if(!file.type.startsWith('image/'))continue;try{photos.push({id:crypto.randomUUID(),dataUrl:await resize(file),caption:''});render()}catch(e){notify((e as Error).message)}}scheduleSave()}
function template(name:keyof typeof TEMPLATES){photos.forEach((p,i)=>p.caption=TEMPLATES[name][i]||'');render();scheduleSave()}
function validate(){if(!address.value.trim()||!hrsz.value.trim())throw new Error('Add meg a címet és a helyrajzi számot.');if(!photos.length)throw new Error('Adj hozzá legalább egy fotót.')}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function savePdf(){try{validate();status.textContent='PDF készítése…';const doc=await buildPdf(session());doc.save(`${fileName()}_fotolap.pdf`);status.textContent='PDF elkészült.'}catch(e){notify((e as Error).message);status.textContent=''}finally{render()}}
function showPreview(){try{validate();preview.replaceChildren();for(let p=0;p<Math.ceil(photos.length/6);p++){const page=document.createElement('section');page.className='preview-page';const head=document.createElement('div');head.className='preview-head';head.textContent=`${formatAddress(address.value)}    hrsz: ${hrsz.value}`;const grid=document.createElement('div');grid.className='preview-grid';photos.slice(p*6,p*6+6).forEach(photo=>{const cell=document.createElement('div');cell.className='preview-cell';const img=document.createElement('img');img.src=photo.dataUrl;img.alt='';const cap=document.createElement('div');cap.textContent=photo.caption||' ';cell.append(img,cap);grid.append(cell)});page.append(head,grid);preview.append(page)}dialog.showModal()}catch(e){notify((e as Error).message)}}

document.querySelector<HTMLDataListElement>('#captionLabels')!.replaceChildren(...LABELS.map(x=>{const o=document.createElement('option');o.value=x;return o}));
$('pickPhotos').onclick=()=>photoInput.click();photoInput.onchange=()=>{if(photoInput.files)addFiles(photoInput.files);photoInput.value=''};
const dz=$('pickPhotos');dz.ondragover=e=>{e.preventDefault();dz.classList.add('drag')};dz.ondragleave=()=>dz.classList.remove('drag');dz.ondrop=e=>{e.preventDefault();dz.classList.remove('drag');if(e.dataTransfer?.files)addFiles(e.dataTransfer.files)};
$('flatTemplate').onclick=()=>template('lakás');$('houseTemplate').onclick=()=>template('ház');$('clearCaptions').onclick=()=>{photos.forEach(p=>p.caption='');render();scheduleSave()};
$('saveSession').onclick=()=>{try{validate();download(new Blob([JSON.stringify(session())],{type:'application/json'}),`${fileName()}_fotolap.json`)}catch(e){notify((e as Error).message)}};
$('loadSession').onclick=()=>sessionInput.click();sessionInput.onchange=async()=>{try{const file=sessionInput.files?.[0];if(!file)return;const data=safeSession(JSON.parse(await file.text()));address.value=data.address;hrsz.value=data.hrsz;photos=data.photos;render();scheduleSave();notify('Munka betöltve.')}catch(e){notify((e as Error).message)}sessionInput.value=''};
$('previewPdf').onclick=showPreview;$('savePdf').onclick=savePdf;$('closePreview').onclick=()=>dialog.close();address.oninput=hrsz.oninput=scheduleSave;
const installButton=$<HTMLButtonElement>('installBtn');const isIos=/iphone|ipad|ipod/i.test(navigator.userAgent);const isStandalone=window.matchMedia('(display-mode: standalone)').matches||(navigator as Navigator&{standalone?:boolean}).standalone===true;if(isIos&&!isStandalone)installButton.hidden=false;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e as BeforeInstallPromptEvent;installButton.hidden=false});installButton.onclick=async()=>{if(deferredInstall){await deferredInstall.prompt();deferredInstall=null}else notify('iPhone-on: Safari → Megosztás → Főképernyőhöz adás')};
registerSW({onNeedRefresh(){notify('Új verzió érhető el. Indítsd újra az appot.')},onOfflineReady(){notify('Az app offline használatra kész.')}});
(async()=>{const saved=await loadLocal().catch(()=>null);if(saved){address.value=saved.address;hrsz.value=saved.hrsz;photos=saved.photos}render()})();
